name: first_flutter_proj
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.0.0
  retrofit: ^4.0.1
  json_annotation: ^4.8.0
  flutter_modular: 6.3.4
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.11
  json_serializable: ^6.0.1
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

# Uncomment and add asset files as needed
# assets:
#   - images/a_dot_burr.jpeg
#   - images/a_dot_ham.jpeg

# Uncomment and add custom fonts as needed
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
